### ISSUE TITLE
static ip url

### ISSUE THREAD

**Issue by Olgerd96** [minsk-hackerspace/spynet#8]
В [README.md](https://github.com/minsk-hackerspace/spynet/blob/master/README.md) написано что есть доменное имя hackerspace.flynet.by которое в теории должно отправлять к статическому IP 91.215.176.168 но это не работает...

PS: если нужно чтобы оно работало предполагаю что @agutikov или @jekhor могут связаться с представителем FlyNet в лице Юрия Сантерского <yuri@flynet.by> по этому вопросу

а если не надо - просто убрать из [README.md](https://github.com/minsk-hackerspace/spynet/blob/master/README.md)

**Comment by abitrolly** [comment]
PTR запись указывает на hackerspace.flynet.by, поэтому и добавилась - её надо прибить на ns1.flynet.by, т.е. к Юре. Потом можно добавить alisa.hackerspace.by на ns1.hoster.by, где сейчас домен хостится.

**Comment by Olgerd96** [comment]
ой... я не внематочный... такой вопрос уже поднимался: #3 (External node IP)

**Comment by Olgerd96** [comment]
Anatoli Babenia, [3 апр. 2017 г., 14:06]: 
Юра пофиксил DNS.
